# The primary workflow that handles validation of pubs and datasets.

name: Main

on: push

jobs:
  main:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Validation
        run: ./_scripts/validate.sh
